version: "3.9"
services:
  db:
   image: "mysql"
   environment:
    MYSQL_HOST: db
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: devcode_backend_test
   volumes:
    - db-data:/var/lib/mysql
   ports:
    - '3306:3306'
  app:
   image: aryagustiana101/devcodebetest:1.0
   environment:
    MYSQL_HOST: db
    MYSQL_PORT: 3306
    MYSQL_USER: root
    MYSQL_PASSWORD: root
    MYSQL_DBNAME: devcode_backend_test
   depends_on:
     - db
   ports:
     - "3030:3030"
volumes:
  db-data: